# Colors
BLACK = 0, 0, 0

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 800, 800

# Independent from screen size, determines
# how big the map will be
TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = 80, 80

INVENTORY_SIZE = INVENTORY_WIDTH, INVENTORY_HEIGHT = (
    600,
    600,
)

INVENTORY_COORDS = INVENTORY_X, INVENTORY_Y = (
    SCREEN_WIDTH // 2 - INVENTORY_WIDTH // 2,
    SCREEN_HEIGHT // 2 - INVENTORY_HEIGHT // 2,
)

SELECTION_BOX_THICKNESS = 20

GRAVITY = 1
JUMP_SPEED = -30
